import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/context/userContext.js";
import { Toaster } from "react-hot-toast";
import MiniSideBar from "@/app/Components/MiniSideBar/MiniSideBar";
import Header from "@/app/Components/Header/Header";
import MainContentLayout from "@/providers/MainContentLayout";
import SideBarProvider from "@/providers/SideBarProvider";
import MainLayout from "@/providers/MainLayout";
import { TasksProvider } from "@/context/taskContext";
import ThemeProvider from "@/providers/ThemeProvider";
import ClientProviders from "@/providers/ClientProviders";
import ProfileUserModal from "./Components/Profile/ProfileUserModal";

const inter = Inter({
  subsets: ["latin"],
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} min-h-screen bg-background text-foreground transition-colors duration-300`}>
        <ThemeProvider>
          <UserContextProvider>
            <TasksProvider>
              <ClientProviders>
                <Toaster position="top-center" />
                
                  <div className="min-h-screen flex">

                    <SideBarProvider>
                      {/*Left mini sidebar */}
                      <MiniSideBar />
                
                      {/* Main Area */}
                      <div className="flex flex-1">
                        <div className="flex flex-1 flex-col">
                          <Header />

                          {/* Content + Right sidebar */}
                          <div className="flex flex-1">

                            {/* Main content area */}
                            <div className="flex-1 p-4 md:p-5 lg:p-6">
                              <MainContentLayout>
                                <MainLayout>
                                  {children}
                                  <ProfileUserModal />
                                </MainLayout>
                              </MainContentLayout>
                            </div>
                          {/* Right sidebar */}
                          {/* (SideBar already inside provider) */}
                          </div>
                        </div>
                      </div>
                    </SideBarProvider>
                  </div>
              </ClientProviders>
            </TasksProvider>
          </UserContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

